/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppMenu: typeof import('./src/components/topbar/AppMenu/index.vue')['default']
    AuthSwiper: typeof import('./src/components/AuthSwiper/AuthSwiper.vue')['default']
    BackToTop: typeof import('./src/components/BackToTop.vue')['default']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardBody: typeof import('bootstrap-vue-next')['BCardBody']
    BCardHeader: typeof import('bootstrap-vue-next')['BCardHeader']
    BCardText: typeof import('bootstrap-vue-next')['BCardText']
    BCardTitle: typeof import('bootstrap-vue-next')['BCardTitle']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormTextarea: typeof import('bootstrap-vue-next')['BFormTextarea']
    BIconEnvelope: typeof import('bootstrap-vue-next')['BIconEnvelope']
    BIconGeoAlt: typeof import('bootstrap-vue-next')['BIconGeoAlt']
    BIconTelephone: typeof import('bootstrap-vue-next')['BIconTelephone']
    BlogNavbar: typeof import('./src/components/navbar/BlogNavbar.vue')['default']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    CartItem: typeof import('./src/components/widgets/CartItem.vue')['default']
    CartOffcanvas: typeof import('./src/components/topbar/CartOffcanvas.vue')['default']
    CustomGLightbox: typeof import('./src/components/CustomGLightbox.vue')['default']
    CustomStickyElement: typeof import('./src/components/CustomStickyElement.vue')['default']
    DemosMenuDropdown: typeof import('./src/components/topbar/AppMenu/DemosMenuDropdown.vue')['default']
    Footer9: typeof import('./src/components/footer/Footer9.vue')['default']
    HelpNavbar: typeof import('./src/components/HelpNavbar.vue')['default']
    ITyped: typeof import('./src/components/ITyped.vue')['default']
    Jarallax: typeof import('./src/components/Jarallax.vue')['default']
    LanguageDropdown: typeof import('./src/components/topbar/LanguageDropdown.vue')['default']
    LogoBox: typeof import('./src/components/topbar/LogoBox.vue')['default']
    MegaMenuDropdown: typeof import('./src/components/topbar/AppMenu/MegaMenuDropdown.vue')['default']
    MenuItem: typeof import('./src/components/topbar/AppMenu/MenuItem.vue')['default']
    MenuItemWithChildren: typeof import('./src/components/topbar/AppMenu/MenuItemWithChildren.vue')['default']
    MobileNavbarToggler: typeof import('./src/components/topbar/MobileNavbarToggler.vue')['default']
    PagesMenuDropdown: typeof import('./src/components/topbar/AppMenu/PagesMenuDropdown.vue')['default']
    Parallax: typeof import('./src/components/Parallax.vue')['default']
    PasswordInput: typeof import('./src/components/PasswordInput.vue')['default']
    PasswordStrengthMeter: typeof import('./src/components/PasswordStrengthMeter.vue')['default']
    PortfolioMenuDropdown: typeof import('./src/components/topbar/AppMenu/PortfolioMenuDropdown.vue')['default']
    ResourcesMenuDropdown: typeof import('./src/components/topbar/AppMenu/ResourcesMenuDropdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShopNavbar: typeof import('./src/components/navbar/ShopNavbar.vue')['default']
    StickyHeader: typeof import('./src/components/topbar/StickyHeader.vue')['default']
    ThemeToggleDropdown: typeof import('./src/components/topbar/ThemeToggleDropdown.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBToggle: typeof import('bootstrap-vue-next')['vBToggle']
  }
}
